# Generated by Django 5.1.3 on 2024-11-17 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkindetails',
            name='checkout_time',
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='checkin_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'from yourapp.models import CustomUser')], default='Employee', max_length=20),
        ),
    ]
