# Generated by Django 5.1.3 on 2024-11-17 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0003_checkindetails_created_by_checkindetails_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='modified_by',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CheckOutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('checkout_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_checkin_app.checkindetails')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
