# Generated by Django 5.1.3 on 2024-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0004_alter_checkindetails_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetails',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CheckOutDetails',
        ),
    ]
