# Generated by Django 5.1.3 on 2024-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0005_checkindetails_checkout_time_delete_checkoutdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'employee')], default='employee', max_length=20),
        ),
    ]
