# Generated by Django 5.1.3 on 2024-11-18 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0008_alter_checkindetails_checkin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='checkin_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
