# Generated by Django 5.1.3 on 2024-11-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0009_alter_checkindetails_checkin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='employee',
            field=models.IntegerField(),
        ),
    ]
