# Generated by Django 5.1.3 on 2024-11-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0010_alter_checkindetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
    ]
