# Generated by Django 5.1.3 on 2024-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0017_remove_checkindetails_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetails',
            name='created_by',
            field=models.CharField(default='admin', max_length=255),
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='employee_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='modified_by',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
