# Generated by Django 5.1.3 on 2024-11-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0018_checkindetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='created_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='modified_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
