# Generated by Django 5.1.3 on 2024-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0020_alter_checkindetails_checkin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='modified_by',
            field=models.CharField(max_length=255),
        ),
    ]
