# Generated by Django 5.1.3 on 2024-11-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_checkin_app', '0021_alter_checkindetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='checkout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
